# Generated by Django 5.1.7 on 2025-03-28 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='poll_image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
