# Generated by Django 5.1.7 on 2025-03-28 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting_app', '0002_poll_poll_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='poll_image',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
